### ISSUE TITLE
lineWidth not work

### ISSUE THREAD

**Issue by LCBbest** [jekorx/vue-canvas-sign#12]
lineWidth not work。
`<canvas-sign :height="130" :width="parentWidth" :borderWidth="0" ref="canvasSign" :lineWidth="50"></canvas-sign>`

**Comment by LCBbest** [comment]
设置宽度等于父div宽度的时候（计算宽度），背景颜色，线条宽度等样式 失效。有什么好的解决方法吗？直接写上宽度样式可以。

**Comment by jekorx** [comment]
@LCBbest 你好，在组件新的版本增加了```reset```方法，组件参数改变后，通过reset方法使属性生效（reset方法会清空画布）
可查看最新版本[![npm package](https://img.shields.io/npm/v/vue-canvas-sign.svg)](https://www.npmjs.com/package/vue-canvas-sign)；如需在```vue@2.x```中使用，请使用 [![vue-canvas-sign@1.0.7](https://img.shields.io/badge/npm%20vue--canvas--sign-v1.0.7-blue)](https://www.npmjs.com/package/vue-canvas-sign/v/1.0.7)
